### ISSUE TITLE
Execution failed calling 'clean build'

### ISSUE THREAD

**Issue by rzabini** [xvik/gradle-quality-plugin#1]
Hi,
if I apply the plugin to my gradle project (environment: gradle wrapper 2.7, Windows 7, Jdk7) without overriding the default configuration directory, when I run `gradlew clean build` I get an 
exception: `java.io.FileNotFoundException: [...] \build\quality-configs\codenarc\codenarc.xml`.

I think that happens because the *ConfigLoader*, which creates the default configuration in the *build* directory, is called at configuration time, before the execution of the *clean* task, which deletes the whole *build* directory.

My current workaround is to add the following to my *build.gradle*:

``` groovy
import ru.vyarus.gradle.plugin.quality.ConfigLoader

clean.doLast {
	(new ru.vyarus.gradle.plugin.quality.ConfigLoader(project)).getCodenarcConfig()
}
```
... but in this way the default configuration file is created twice: during gradle configuration and during gradle execution. Would it be possible to execute it only during the execution phase, instead?
Thank you

**Comment by xvik** [comment]
Thank you very much for the info! 
Fix released with version 1.0.3
