### ISSUE TITLE
Disable output on the console

### ISSUE THREAD

**Issue by dovogt** [xvik/gradle-quality-plugin#11]
When you run Checkstyle, PMD, and Spotbugs, the messages are output to the console. Is it possible to suppress the messages? The logfiles become very big. That's why I would like to activate it.

Console output:
**checkstyle**
```
[Coding | MultipleStringLiterals] de.alpha.util.(ExportToolsTest.java:32)
  Der String "c:/temp/test.zip" wird in dieser Datei 3-mal verwendet.
  http://checkstyle.sourceforge.net/config_coding.html#MultipleStringLiterals
```

**pmd**
```
[Best Practices | AvoidReassigningParameters] de.alpha.kit.web.fe.servlets.(CSSStyleServlet.java:654)
  Avoid reassigning parameters such as 'col2'
  https://pmd.github.io/pmd-6.7.0/pmd_rules_java_bestpractices.html#avoidreassigningparameters
```

**spotbugs**
```
[Dodgy code | ST_WRITE_TO_STATIC_FROM_INSTANCE_METHOD] de.alpha.webservice.webserver.(JavaWebservice.java:112)  [priority 1]
	>> Write to static field de.alpha.webservice.webserver.JavaWebservice.serverConfig from instance method de.alpha.webservice.webserver.JavaWebservice.configure(String, String, String, String)
  This instance method writes to a static field. This is tricky to get
  correct if multiple instances are being manipulated,
  and generally bad practice.
```

**Comment by xvik** [comment]
Yes, of course:
```groovy
quality.consoleReporting = false
```
[Docs](http://xvik.github.io/gradle-quality-plugin/3.2.0/guide/config/#disable-console-output)

**Comment by dovogt** [comment]
Hello,
I have it active. The mediations will still be displayed

![image](https://user-images.githubusercontent.com/25249296/48931504-f84d9680-eef6-11e8-90ea-8ed29ef8d1a2.png)

**Comment by dovogt** [comment]
I have only one project. It may be that the high-priority warnings are still output to the console? The problem I have since Gradle 3. * Currently I use gradle 4.10.2 and quality plugin 3.2.0

`quality {
	/**
	 * When disabled, quality plugins will not be registered automatically (according to sources).
	 * Only manualy registered quality plugins will be configured.
	 */
	boolean autoRegistration = true

	// Enable/disable tools (when auto registration disabled control configuration appliance)
	checkstyle = true
	spotbugs = true
	pmd = true
	codenarc = false

	// Tools versions
	checkstyleVersion = '8.12'
	spotbugsVersion = '3.1.8'
	pmdVersion = '6.7.0'

	/**
	 * The analysis effort level. The value specified should be one of min, default, or max.
	 * Higher levels increase precision and find more bugs at the expense of running time and
	 * memory consumption. Default is 'max'.
	 */
	spotbugsEffort = 'max'

	/**
	 * The priority threshold for reporting bugs.
	 * If set to low, all bugs are reported.
	 * If set to medium, medium and high priority bugs are reported.
	 * If set to high, only high priority bugs are reported. Default is 'medium'.
	 */
	spotbugsLevel = 'high'

	/**
	 * Javac lint options to show compiler warnings, not visible by default.
	 * Applies to all CompileJava tasks.
	 * Options will be added as -Xlint:option
	 * Full list of options: http://docs.oracle.com/javase/8/docs/technotes/tools/windows/javac.html#BHCJCABJ
	 */
	lintOptions = []

	/**
	 * When false, no html reports will be built. True by default.
	 */
	htmlReports = false

	/**
	 * Strict quality leads to build fail on any violation found. If disabled, all violation
	 * are just printed to console.
	 */
	strict = false

	/**
	 * When false, disables quality tasks execution. Allows disabling tasks without removing plugins.
	 * Quality tasks are still registered, but skip execution, except when task called directly or through
	 * checkQualityMain (or other source set) grouping task.
	 */
	boolean enabled = true

	/**
	 * When false, disables reporting quality issues to console. Only gradle general error messages will
	 * remain in logs. This may be useful in cases when project contains too many warnings.
	 * Also, console reporting require xml reports parsing, which could be time consuming in case of too
	 * many errors (large xml reports).
	 * True by default.
	 */
	boolean consoleReporting = false

	/**
	 * Source patterns (relative to source dir) to exclude from checks. Simply sets exclusions to quality tasks.
	 *
	 * Animalsniffer is not affected because
	 * it's a different kind of check (and, also, it operates on classes so source patterns may not comply).
	 *
	 * Findbugs does not support exclusion directly, but plugin will resolve excluded classes and apply
	 * them to xml exclude file (default one or provided by user).
	 *
	 * By default nothing is excluded.
	 *
	 * IMPORTANT: Patterns are checked relatively to source set dirs (not including them). So you can only
	 * match source files and packages, but not absolute file path (this is gradle specific, not plugin).
	 *
	 * @see org.gradle.api.tasks.SourceTask#exclude(java.lang.Iterable) (base class for all quality tasks)
	 */
	exclude = ['**/*ClassInfo.java']

	/**
	 * Direct sources to exclude from checks (except animalsniffer).
	 * This is useful as last resort, when extension or package is not enough for filtering.
	 * Use {@link Project#files(java.lang.Object)} or {@link Project#fileTree(java.lang.Object)}
	 * to create initial collections and apply filter on it (using
	 * {@link org.gradle.api.file.FileTree#matching(groovy.lang.Closure)}).
	 *
	 * Plugin will include files into findbugs exclusion filter xml (default one or provided by user).
	 *
	 * Note: this must be used when excluded classes can't be extracted to different source set and
	 * filter by package and filename is not sufficient.
	 */
	//excludeSources


	/**
	 * Source sets to apply checks on.
	 * Default is [sourceSets.main] to apply only for project sources, excluding tests.
	 */
	//sourceSets

	/**
	 * User configuration files directory. Files in this directory will be used instead of default (bundled) configs.
	 */
	configDir = 'gradle/config/'
}`

**Comment by xvik** [comment]
Mmm, I think I got your situation. If this is exact extract from your build file then its incorrect (and it's my bad).

Before, I put part of source code (extension class) into the documentation (and seems you copy pasted it from old doc). [New doc](http://xvik.github.io/gradle-quality-plugin/3.2.0/guide/config/) is correct.

Look, for example, 
```groovy
quality {
   boolean autoRegistration = true
}
```
For gradle is local variable declaration, which doesn't actually do anything, and 
```groovy
quality {
   autoRegistration = true
}
```
is *quality extension configuration* (changing it's value).

So please remove all **boolean** in your config so only property names remain (like [in docs](http://xvik.github.io/gradle-quality-plugin/3.2.0/guide/config/)) and `consoleReporting = false` will work correctly.

Sorry for misguiding.

**Comment by dovogt** [comment]
Oh sorry,  I did not see that. Now it works :-) Thank you
