### ISSUE TITLE
Check JUnit-Tests with separate rules

### ISSUE THREAD

**Issue by dovogt** [xvik/gradle-quality-plugin#14]
Can I specify that I want to check the JUnit tests with other rules, like the source?  For example, in PMD there are rules that you can use to check JUnit tests. But for the "normal" code you can't use them.  For example, all methodes that do not have a test as annotation are marked as faulty.

Can I do this with the plugin or are there other possibilities?

**Comment by xvik** [comment]
Right now there is only one configuration supported for all source sets (all gradle quality plugins use unified configuration by default). The only way to differentiate configs is to manually change configuration for test scope tasks: (something like)
```groovy
afterEvaluate {
    pmdTest.ruleSetFiles = files('path/to/custom.xml')
}
```

The most obvious improvement that comes to my mind is to introduce postfixes for configuration files. For example, right now pmd config is searched as `$configDir/pmd/pmd.xml` (applied for all pmd tasks), but plugin can look for source set specific files first like `$configDir/pmd/pmd-main.xml` or `$configDir/pmd/pmd-test.xml` (according to context source set) and apply default file only if specific file not found. Of course, it wold be supported for all config files. 

Will it be a good enough solution? I did not use quality tools on tests and so I can only guess if it will be enough.

**Comment by dovogt** [comment]
Thank you for your answer. I would try it that way. Where do I have to call afterEvaluate. In the qualityTask? I have stored the default sourceset and can only specify one sourceset.  How can I specify main and source? 
/**
	 * Source sets to apply checks on.
	 * Default is [sourceSets.main] to apply only for project sources, excluding tests.
 */

Can I use it for checkstyle and find bugs as well?


```
quality {
	/**
	 * When disabled, quality plugins will not be registered automatically (according to sources).
	 * Only manualy registered quality plugins will be configured.
	 */
	boolean autoRegistration = true

	// Enable/disable tools (when auto registration disabled control configuration appliance)
	checkstyle = true
	spotbugs = true
	pmd = true
	codenarc = false

	// Tools versions
	checkstyleVersion = '8.16'
	spotbugsVersion = '3.1.10'
	pmdVersion = '6.10.0'

	/**
	 * The analysis effort level. The value specified should be one of min, default, or max.
	 * Higher levels increase precision and find more bugs at the expense of running time and
	 * memory consumption. Default is 'max'.
	 */
	spotbugsEffort = 'max'

	/**
	 * The priority threshold for reporting bugs.
	 * If set to low, all bugs are reported.
	 * If set to medium, medium and high priority bugs are reported.
	 * If set to high, only high priority bugs are reported. Default is 'medium'.
	 */
	spotbugsLevel = 'high'

	/**
	 * Javac lint options to show compiler warnings, not visible by default.
	 * Applies to all CompileJava tasks.
	 * Options will be added as -Xlint:option
	 * Full list of options: http://docs.oracle.com/javase/8/docs/technotes/tools/windows/javac.html#BHCJCABJ
	 */
	lintOptions = []

	/**
	 * When false, no html reports will be built. True by default.
	 */
	htmlReports = false

	/**
	 * Strict quality leads to build fail on any violation found. If disabled, all violation
	 * are just printed to console.
	 */
	strict = false

	/**
	 * When false, disables quality tasks execution. Allows disabling tasks without removing plugins.
	 * Quality tasks are still registered, but skip execution, except when task called directly or through
	 * checkQualityMain (or other source set) grouping task.
	 */
	enabled = true

	/**
	 * When false, disables reporting quality issues to console. Only gradle general error messages will
	 * remain in logs. This may be useful in cases when project contains too many warnings.
	 * Also, console reporting require xml reports parsing, which could be time consuming in case of too
	 * many errors (large xml reports).
	 * True by default.
	 */
	consoleReporting = false

	/**
	 * Source patterns (relative to source dir) to exclude from checks. Simply sets exclusions to quality tasks.
	 *
	 * Animalsniffer is not affected because
	 * it's a different kind of check (and, also, it operates on classes so source patterns may not comply).
	 *
	 * Findbugs does not support exclusion directly, but plugin will resolve excluded classes and apply
	 * them to xml exclude file (default one or provided by user).
	 *
	 * By default nothing is excluded.
	 *
	 * IMPORTANT: Patterns are checked relatively to source set dirs (not including them). So you can only
	 * match source files and packages, but not absolute file path (this is gradle specific, not plugin).
	 *
	 * @see org.gradle.api.tasks.SourceTask#exclude(java.lang.Iterable) (base class for all quality tasks)
	 */
	exclude = ['**/*ClassInfo.java']

	/**
	 * Direct sources to exclude from checks (except animalsniffer).
	 * This is useful as last resort, when extension or package is not enough for filtering.
	 * Use {@link Project#files(java.lang.Object)} or {@link Project#fileTree(java.lang.Object)}
	 * to create initial collections and apply filter on it (using
	 * {@link org.gradle.api.file.FileTree#matching(groovy.lang.Closure)}).
	 *
	 * Plugin will include files into findbugs exclusion filter xml (default one or provided by user).
	 *
	 * Note: this must be used when excluded classes can't be extracted to different source set and
	 * filter by package and filename is not sufficient.
	 */
	//excludeSources


	/**
	 * Source sets to apply checks on.
	 * Default is [sourceSets.main] to apply only for project sources, excluding tests.
	 */
	//sourceSets

	/**
	 * User configuration files directory. Files in this directory will be used instead of default (bundled) configs.
	 */
	configDir = 'gradle/config/'
	
	afterEvaluate {
    	pmdTest.ruleSetFiles = files('gradle/config/pmd/pmd-test.xml')
	}	
}
```

**Comment by xvik** [comment]
It is pure gradle configuration and not part of the quality plugin configuration:
```groovy
quality {
   ....
}
afterEvaluate {
    	pmdTest.ruleSetFiles = files('gradle/config/pmd/pmd-test.xml')
}
```

`afterEvaluate` part is required to delay configuration because quality plugin works after initial configuration and to override configured tasks, manual configuration [must go even further](http://xvik.github.io/gradle-quality-plugin/3.4.0/guide/config/#configuration-override).

Inside `afterEvaluate` you apply direct tasks configuration. in teh example above it is [`pmdTest` task direct configuration](https://docs.gradle.org/current/userguide/pmd_plugin.html#sec:pmd_tasks)

The same way you can modify config for other tools. E.g. for [checkstyle](https://docs.gradle.org/current/userguide/checkstyle_plugin.html#sec:checkstyle_tasks):
```groovy
afterEvaluate {
     pmdTest.ruleSetFiles = files('gradle/config/pmd/pmd-test.xml')
     checkstyleTest.configFile = file('gradle/config/checkstyle/checkstyle-test.xml')
}
```

[Findbugs configuration](https://docs.gradle.org/current/userguide/findbugs_plugin.html#sec:findbugs_tasks) is different because it does not have direct rules file, instead it use efforts level + rules exclusions file. 
Example modification (assume it's under afterEvaluate): 
```groovy
findbugsTest.with {
    reportLevel = 'hight'
    excludeFilter = file('gradle/config/findbugs/findbugs-exclude-test.xml')
}
```

**Comment by dovogt** [comment]
Very nice. It worked like this.  Many thanks :-) I noticed that when calling the task check, only checkQualityMain is called and not checkQualityTest.
