### ISSUE TITLE
Configuring Spotbugs ReportLevel

### ISSUE THREAD

**Issue by dovogt** [xvik/gradle-quality-plugin#15]
Can I use the plugin to specify the reportlevel at which the messages are displayed and what is the default reportlevel like?

thx

**Comment by xvik** [comment]
Yes, [you can configure it](http://xvik.github.io/gradle-quality-plugin/3.4.0/tool/spotbugs/#config)

`effort - 
The analysis effort level. The value specified should be one of min, default, or max. Higher levels increase precision and find more bugs at the expense of running time and memory consumption.`

`reportLevel -
The priority threshold for reporting bugs. If set to low, all bugs are reported. If set to medium (the default), medium and high priority bugs are reported. If set to high, only high priority bugs are reported.`

Quotes from [gradle docs](http://gradle.monochromeroad.com/docs/dsl/org.gradle.api.plugins.quality.FindBugsExtension.html) (for findbugs plugin, but it's the same for spotbugs)

**Comment by dovogt** [comment]
I used the two switches.  Besides Gradle we also use the EclipsePlugin. There is another setting in Eclipse, which causes the results to differ between Gradle and Eclipse.

![image](https://user-images.githubusercontent.com/25249296/55220944-b916b580-5208-11e9-949d-72823813420c.png)

**Comment by xvik** [comment]
Spotbugs plugin did not allow to filter by ranks directly, but it is possible through filters.
Quality plugin automatically apply only exclude filter, but you'll need include filter, so you'll have to configure it manually:
```groovy
afterEvaluate {
     spotbugs.includeFilter = file("${quality.configDir}/spotbugs/includeFilter.xml")
}
```
includeFilter.xml:
```xml
<FindBugsFilter>
     <Match>
         <Rank value="15"/>
     </Match>
</FindBugsFilter>
```
After that only 15-20 ranks should be reported. I did not test it myself, just used [this source](https://dzone.com/articles/filtering-findbugs-reports)

Generally support for this should be added directly to plugin:
1. add inclusion filter file support 
2. add `spotbugsMinRank=12` (probably)

**Comment by dovogt** [comment]
Thank you so much for your trouble. I'll give it a try.

**Comment by xvik** [comment]
I was wrong, rank rule must be applied in exclusions filter, not in inclusion filter (or it should be inverted in inclusion filter).

New version will provide special setting for rank filtering:
```groovy
quality{
    spotbugsMaxRank = 15
}
```
(means violations with ranks 16-20 will be filtered)

Also, ranks are shown now in console report:

```
[Performance | URF_UNREAD_FIELD] sample.(Sample.java:11)  [priority 2 / rank 18]
	>> Unread field: sample.Sample.sample
  This field is never read. Consider removing it from the class.
```

**Comment by dovogt** [comment]
Thank you.  Can you tell when the new version will be released?

**Comment by xvik** [comment]
Ideally, just after pmd [6.20](https://github.com/pmd/pmd/milestone/37) release. There is a bug with [very confusing warning](https://github.com/pmd/pmd/issues/2096). 

But, maybe, I'll simply downgrade to 6.18 and release.. not sure now.
