### ISSUE TITLE
gradle 6: quality plugin breaks build because FindBugs has been removed

### ISSUE THREAD

**Issue by eekboom** [xvik/gradle-quality-plugin#18]
After updating to gradle 6, I get this error 

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'xlcalc'.
> Failed to notify project evaluation listener.
   > org/gradle/api/plugins/quality/FindBugsPlugin
```

We have disabled FindBugs in the configuration anyway.

gradle 6 removed the plugin completey, see https://docs.gradle.org/current/userguide/upgrading_version_5.html#the_findbugs_plugin_has_been_removed
Could you release a version of the quality plugin that does not rely on FindBugs being present?

**Comment by eekboom** [comment]
Sorry, only now found #17  where this has already been reportred.

**Comment by xvik** [comment]
No problem, thank you for the notification anyway! 
I was afraid that it was a mistake to close that ticket before release)

The new version will be released today or tomorrow.
