### ISSUE TITLE
plugin breaks gradle integration in IntelliJ IDEA 2020.1 EAP

### ISSUE THREAD

**Issue by eekboom** [xvik/gradle-quality-plugin#21]
When I try to sync/reimport my gradle project in latest Idea Early Access version, the Sync fails with:

> java.util.NoSuchElementException: Cannot access last() element from an empty List
>         at ru.vyarus.gradle.plugin.quality.QualityPlugin$_applyEnabledState_closure14.doCall(QualityPlugin.groovy:458)
> 

It seems IDEA now invokes gradle without passing any tasks and that makes the quality plugin fail.

The same can be observed if you run the initialization and configuration phase only from the command line. 
I don't know if there's a dedicated way to not execute any tasks, but for example this command gives the same exception:
`./gradlew build - x build`

**Comment by xvik** [comment]
Thank you! I reproduced the problem.

But the problem appears only if quality plugin is disabled with `quality.enabled = false`. In this case, quality tasks could be only executed directly and not included in the `build` sequence. 

Before the new version release, you can use `quality.strict=false` instead. This way all checks will be executed on build, but will not fail it. Or you can disable exact tools like `quality.pmd = false`.

**Comment by eekboom** [comment]
Thanks a lot for the quick fix!
We have indeed disabled the plugin in one of the modules that contains only generated sources.
For now, I used quality.pmd = false as a workaround.

**Comment by xvik** [comment]
4.1.0 [released](https://github.com/xvik/gradle-quality-plugin/releases/tag/4.1.0)
