### ISSUE TITLE
Feature request: dependency checks for vulnerabilities

### ISSUE THREAD

**Issue by binkley** [xvik/gradle-quality-plugin#25]
I am really appreciating the Quality plugin!

Have you considered including security vulnerability checks, ala https://github.com/jeremylong/dependency-check-gradle?

I use this plugin on most of my Gradle projects.

**Comment by xvik** [comment]
Quality plugin unifies configuration for quality tools and maintains the default config in the actual state for new tool versions (I believe config files are the main blocking factor for many devs against using quality tools).

What quality plugin could simplify for dependency-check plugin? 
Automatic activation of 3rd party plugin is a bad idea. Hidden activation of spotbugs plugin already causes problems (almost all implicit actions cause problems eventually), but its unavoidable evil.

Applying dependency-check plugin manually is just 1 line (I tried it; it even does not require any configuration by default). 
I don't see any cases where quality plugin could simplify anything. 

p.s. There is a [snyk](https://snyk.io/) service which completely automates dependencies security check.  It can't correctly work with BOMs, but for simple projects, it's a very good option. Just as an example that in contrast to source quality tools where almost no alternatives exist, the situation for dependencies check is different.
