### ISSUE TITLE
Update CodeNarc to latest version (1.6.1)

### ISSUE THREAD

**Issue by jjathman** [xvik/gradle-quality-plugin#28]
The main reason for updating to this version is that it updates to a version of Groovy that works better with "standard" Spring Boot applications that use the Spring dependency management plugin. 

The current version in of CodeNarc being used by the quality plugin pulls in a version of CodeNarc that uses an old version of Groovy which used to bundle everything as a single Jar. After Groovy 2.4, the Groovy modules were broken up in to smaller pieces. 

Additionally, it would be nice to use the latest CodeNarc features including Groovy 3.x support.

**Comment by xvik** [comment]
Sure, will do. Just a bit later (I'm on vacation now, plus need to fix spotbugs support)

**Comment by jjathman** [comment]
No problem at all, thank you very much!
