### ISSUE TITLE
Provide configDirectory property for Checkstyle plugin

### ISSUE THREAD

**Issue by baev** [xvik/gradle-quality-plugin#29]
This property is required in order to have `config_loc` variable set, for example to use it with SuppressionFilter module:

```
<module name="SuppressionFilter">
    <property name="file" value="${config_loc}/suppressions.xml"/>
</module>
```

https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.CheckstyleExtension.html#org.gradle.api.plugins.quality.CheckstyleExtension:configDirectory

FYI: as workaround I use afterEvaluate to pass configDirectory to Checkstyle and it works just fine

**Comment by xvik** [comment]
`checkstyle.configDirectory` set to `gradle/config/checkstyle/` (by default)

Also, suppressions filter added to the default file:

```xml
<module name="SuppressionFilter">
        <property name="file" value="${config_loc}/suppressions.xml"/>
        <property name="optional" value="true"/>
</module>
``` 
(with optional=true to ignore absent file)

So it would be enough now to just drop custom suppressions.xml into `gradle/config/checkstyle/` and it would be used automatically.
