### ISSUE TITLE
Support copy-paste-detector

### ISSUE THREAD

**Issue by dovogt** [xvik/gradle-quality-plugin#4]
Is it possible for the plugin to support CPD (copy-paste-detector)? 
https://pmd.github.io/pmd-6.2.0/#cpd

**Comment by xvik** [comment]
CDP plugin will be supported in the new version. Cpd project is assumed to be applied manually, so  quality plugin applies configurations only if plugin exists (no automatic registrations):
* cpd.toolVersion = quality.pmdVersion
* cpd.ignoreFailures = !quality.strict
* cpdCheck.source synchronized with configured sourceSets and exclusions (same scope as all other quality plugins). May be disabled with quality.cpdUnifySources
* Custom console report (like for other tools)
* HTML report (generated with style recommended by pmd)
* cpdCheck always associated with check task

For multi-module projects, it is assumed that cpd plugin will be declared in root project (as plugin author suggests) and quality plugins will be applied in subprojects. In this case, cpd plugin will be also configured. cpdCheck task source will also be affected: each submodule will exclude not needed sources and so for each module cpd "scope" will be the same as for other quality plugins.

Submodule check will depend on root cpdCheck (again, as suggested by plugin author)

In case of multiple cpd tasks declared, each task will have custom console reporting + html report.
But only default cpdCheck task sources are affected.

Cpd configuration supposed to be performed in cpd closure (quality plugin does not affect it)
