### ISSUE TITLE
 Configure output format

### ISSUE THREAD

**Issue by dovogt** [xvik/gradle-quality-plugin#5]
Currently the results are output in xml and html format. A central switch that controls whether the output is in HTML or XML. I have large output files and process them on the Jenkins builds

**Comment by xvik** [comment]
Xml reports are required for console reporting, but I will provide an option to switch off html reporting (like `quality.htmlReports = false`).

I suppose large outputs indicates a lot of warnings. In this case, you can simply disable quality checks with [`quality.enabled=false`](http://xvik.github.io/gradle-quality-plugin/3.0.0/guide/config/#disable-quality-plugins) (no quality tasks will be executed at all). 

I don't see any sense to use quality tools when you don't fix warnings. And if you plan to fix them then you can use quality tools locally (quality tasks will work when called directly even when quality is disabled, e.g. with [group task](http://xvik.github.io/gradle-quality-plugin/3.0.0/task/group/)) and only after that enable quality checks on jenkins (in strict mode to fail build if new warnings appear).

**Comment by dovogt** [comment]
It's about deactivating the HTML output. The graphic processing takes over Jenkins and needs only the XML files.
