### ISSUE TITLE
Could not find SpotBugs

### ISSUE THREAD

**Issue by ibogolyubskiy** [xvik/gradle-quality-plugin#6]
My root project gradle file:
```
buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.1'
        classpath 'com.google.gms:google-services:3.0.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files

        classpath 'ru.vyarus:gradle-quality-plugin:3.0.0'
    }
}
apply plugin: 'ru.vyarus.quality'
```
gives this error:

> Could not find gradle.plugin.com.github.spotbugs:spotbugs-gradle-plugin:1.6.1.
Searched in the following locations:
    https://jcenter.bintray.com/gradle/plugin/com/github/spotbugs/spotbugs-gradle-plugin/1.6.1/spotbugs-gradle-plugin-1.6.1.pom
    https://jcenter.bintray.com/gradle/plugin/com/github/spotbugs/spotbugs-gradle-plugin/1.6.1/spotbugs-gradle-plugin-1.6.1.jar
    https://dl.google.com/dl/android/maven2/gradle/plugin/com/github/spotbugs/spotbugs-gradle-plugin/1.6.1/spotbugs-gradle-plugin-1.6.1.pom
    https://dl.google.com/dl/android/maven2/gradle/plugin/com/github/spotbugs/spotbugs-gradle-plugin/1.6.1/spotbugs-gradle-plugin-1.6.1.jar
Required by:
    project : > ru.vyarus:gradle-quality-plugin:3.0.0

**Comment by xvik** [comment]
You need to add [gradlePluginPortal()](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/dsl/RepositoryHandler.html#gradlePluginPortal--) repository as plugin is available only there:

```groovy
repositories {
        jcenter()
        google()
        gradlePluginPortal()
    }
```
I will mention it to docs, thank you

**Comment by ibogolyubskiy** [comment]
Thanks, it works!
